begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(55);

select is((select count(*)::int from public.clients),10,'Fixture contains exactly 10 clients');
select is((select count(*)::int from public.projects),25,'Fixture contains exactly 25 projects');
select is((select count(distinct service_type)::int from public.projects),20,'Every catalog service is exercised');
select is((select count(*)::int from public.credit_ledger where kind='project_debit'),25,'Every fixture project has one debit');
select ok(not exists(select 1 from public.credit_months m where m.balance<>(select coalesce(sum(l.amount),0) from public.credit_ledger l where l.client_id=m.client_id and l.month=m.month)),'Balances reconcile with the ledger');

set local role anon;
select throws_ok('select * from public.clients','42501',null,'Anonymous users cannot read clients');
select ok(not has_function_privilege('anon','public.accept_briefing(uuid,date)','execute'),'Anonymous users cannot execute workflows');
reset role;
select set_config('request.jwt.claim.sub',md5('dawes:client-8')::uuid::text,true);
set local role authenticated;
select is((select count(*)::int from public.clients),1,'Client sees only its client workspace');
select is((select count(*)::int from public.projects),7,'Client sees its seven projects');
select is((select count(*)::int from public.profiles),1,'Client cannot enumerate staff profiles');
select is((select count(*)::int from public.project_assignments),0,'Client cannot discover designer assignments');
select is((select count(*)::int from public.design_versions),0,'Client cannot read production versions');
select hasnt_table('public','designs','Uploaded production designs are retired');
select is((select count(*)::int from public.internal_comments),0,'Client cannot read internal comments');
select is((select count(*)::int from public.credit_accounts),1,'Client can read only its credit account');
select ok(not exists(select 1 from public.published_versions where project_id not in(select id from public.projects)),'Client sees no cross-tenant client versions');
select is((select count(*)::int from public.brand_sections),8,'Brand sections are tenant scoped');
select is((select count(*)::int from public.template_drafts),1,'Personal drafts are owner scoped');
select throws_ok('select * from private.publication_sources','42501',null,'Client cannot read publication source mapping');
select throws_ok($$update public.profiles set role='agency' where id=auth.uid()$$,'42501',null,'Client cannot promote its role');
select throws_ok($$select public.adjust_credits(md5('dawes:client-org-8')::uuid,100,'Unauthorized','attack')$$,'42501','Agency access required','Client cannot grant credits');
select throws_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'internal','Attack')$$,'42501','Internal channel access required','Client cannot post internally');
select throws_ok($$select public.post_comment(md5('dawes:project-4')::uuid,'client','Attack')$$,'42501','Client channel access required','Client cannot post across tenants');
select throws_ok($$select public.share_miro_version(md5('dawes:project-sabre-campaign-landing-page')::uuid,'https://miro.com/app/board/uXjVAttack1=/')$$,'42501','Agency access required','Client cannot share a client version');
select throws_ok($$update public.credit_accounts set balance=9999$$,'42501',null,'Balances cannot be updated directly');
select hasnt_table('public','published_designs','Uploaded client snapshots are retired');
select ok(not exists(select 1 from public.client_comments where author_kind='studio' and author_label<>'Studio'),'Agency messages use Studio identity');
select lives_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'client','The direction looks good.')$$,'Client can post in its client channel');
select hasnt_column('public','client_comments','pin_x','Client comments carry no pin');
select throws_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'client','Old pin call',null,null,0.5,0.5,null,null)$$,'42883',null,'The design and pin arguments are gone');
select throws_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'client','Cross-project version',md5('dawes:publication-4')::uuid)$$,'23503',null,'Cross-project publication references are rejected');

reset role;
select set_config('request.jwt.claim.sub',md5('dawes:designer-1')::uuid::text,true);
set local role authenticated;
select is((select count(*)::int from public.projects),12,'Designer sees exactly its assigned projects');
select is((select count(*)::int from public.credit_accounts),0,'Designer cannot read balances');
select is((select count(*)::int from public.credit_ledger),0,'Designer cannot read credit transactions');
select is((select count(*)::int from public.client_comments),0,'Designer cannot read client conversations');
select is((select count(*)::int from public.published_versions),0,'Designer cannot enumerate client publication records');
select throws_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'client','Attack')$$,'42501','Client channel access required','Designer cannot post in client channel');
select throws_ok($$select public.share_miro_version(md5('dawes:project-sabre-campaign-landing-page')::uuid,'https://miro.com/app/board/uXjVAttack1=/')$$,'42501','Agency access required','Designer cannot share a client version');
select throws_ok($$select public.post_comment(md5('dawes:project-3')::uuid,'internal','Attack')$$,'42501','Internal channel access required','Designer cannot comment on another assignment');
select lives_ok($$select public.post_comment(md5('dawes:project-sabre-campaign-landing-page')::uuid,'internal','Ready for studio review.')$$,'Assigned designer can comment internally');

reset role;
select set_config('request.jwt.claim.sub',md5('dawes:agency')::uuid::text,true);
set local role authenticated;
select is((select count(*)::int from public.clients),10,'Agency sees all clients');
select throws_ok($$select public.accept_briefing(md5('dawes:pending-2')::uuid)$$,'P0001','Confirm the budget before accepting','Acceptance requires budget confirmation');
select throws_ok($$select public.confirm_briefing_budget(md5('dawes:pending-2')::uuid,4)$$,'P0001','Explain any adjustment to estimated credits','Budget changes require justification');
select lives_ok($$select public.confirm_briefing_budget(md5('dawes:pending-2')::uuid,4,'Additional format adaptation.')$$,'Agency confirms a justified budget');
select lives_ok($$select public.accept_briefing(md5('dawes:pending-2')::uuid)$$,'Confirmed briefing creates a project');
select is(public.accept_briefing(md5('dawes:pending-2')::uuid),(select id from public.projects where briefing_id=md5('dawes:pending-2')::uuid),'Repeated acceptance returns the same project');
select is((select count(*)::int from public.credit_ledger where project_id=(select id from public.projects where briefing_id=md5('dawes:pending-2')::uuid)),1,'Repeated acceptance creates exactly one debit');
select throws_ok($$select public.accept_briefing(md5('dawes:pending-3')::uuid)$$,'P0001','Insufficient credit balance','Insufficient balance rejects acceptance');
select is((select count(*)::int from public.projects where briefing_id=md5('dawes:pending-3')::uuid),0,'Failed acceptance creates no project');
select lives_ok($$select public.share_miro_version(md5('dawes:project-sabre-campaign-landing-page')::uuid,'https://miro.com/app/board/uXjVAccept1=/?moveToWidget=7','Second direction',null,md5('aw:share-1')::uuid)$$,'Agency shares a client version');
select is(public.share_miro_version(md5('dawes:project-sabre-campaign-landing-page')::uuid,'https://miro.com/app/board/uXjVAccept1=/?moveToWidget=7','Second direction',null,md5('aw:share-1')::uuid),(select publication_id from public.publication_miro_links where board_id='uXjVAccept1='),'Share retries return the existing client version');
select throws_ok($$update public.published_versions set release_note='Changed'$$,'42501',null,'Client versions cannot be updated directly');
select is((select status::text from public.projects where id=md5('dawes:project-sabre-campaign-landing-page')::uuid),'client_review','Sharing puts the project in client review');
select is((select status from public.publication_reviews r join public.publication_miro_links l on l.publication_id=r.publication_id where l.board_id='uXjVAccept1='),'pending','A shared version opens a pending client review');
select ok(not exists(select 1 from public.credit_months m where m.balance<>(select coalesce(sum(l.amount),0) from public.credit_ledger l where l.client_id=m.client_id and l.month=m.month)),'Workflow operations leave balances reconciled');
select * from finish();
rollback;
