begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
set local storage.allow_delete_query='true';
select plan(8);
select set_config('request.jwt.claim.sub',md5('dawes:agency')::uuid::text,true);
set local role authenticated;
select lives_ok($$insert into storage.objects(bucket_id,name,owner_id) values('brand-assets',md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.png',auth.uid()::text)$$,'Agency can upload a client logo');
select lives_ok($$update public.clients set logo_path=md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.png' where id=md5('dawes:client-org-1')::uuid$$,'Agency can set a client logo');
select throws_ok($$update public.clients set logo_path=md5('dawes:client-org-2')::uuid::text||'/'||md5('logo-test')::uuid::text||'.png' where id=md5('dawes:client-org-1')::uuid$$,'23514',null,'A logo outside the client scope is rejected');
select throws_ok($$update public.clients set logo_path=md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.pdf' where id=md5('dawes:client-org-1')::uuid$$,'23514',null,'A logo must be an image');
select throws_ok($$update public.clients set logo_path=md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.svg' where id=md5('dawes:client-org-1')::uuid$$,'23514',null,'A logo cannot be an SVG');
delete from storage.objects where bucket_id='brand-assets' and name=md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.png';
reset role;
select is((select count(*)::int from storage.objects where name=md5('dawes:client-org-1')::uuid::text||'/'||md5('logo-test')::uuid::text||'.png'),1,'A referenced logo file cannot be deleted');
select set_config('request.jwt.claim.sub',md5('dawes:client-1')::uuid::text,true);
set local role authenticated;
select is((select logo_path is not null from public.clients where id=md5('dawes:client-org-1')::uuid),true,'Client can read its own logo path');
update public.clients set logo_path=null where id=md5('dawes:client-org-1')::uuid;
reset role;
select isnt((select logo_path from public.clients where id=md5('dawes:client-org-1')::uuid),null,'Client cannot change its logo');
select * from finish();
rollback;
