begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
create temporary table pb(key text primary key,value uuid);
grant all on pb to authenticated;
insert into pb select name,md5('pb:'||name)::uuid from unnest(array['agency','client','designer','other','client-org','project','brief','board','other-board','draft-key','send-key','edit-key','send2-key']) name;
create function pg_temp.k(p text) returns uuid language sql as $$select value from pb where key=p$$;
create function pg_temp.act(p text) returns text language sql as $$select set_config('request.jwt.claim.sub',pg_temp.k(p)::text,true)$$;
create function pg_temp.content() returns jsonb language sql as $$select '{"title":"Studio concepts","serviceId":"social","overview":"Create three distinct options","goals":"Explore directions","direction":{"audience":"Internal audience","notes":"Studio notes"},"deliverables":[{"name":"Concept options","format":"feed","quantity":3,"scope":"original","width":1080,"height":1350}],"dueDate":"2026-10-01","references":[{"name":"Reference","url":"https://example.com/reference"}]}'::jsonb$$;
insert into auth.users(id,email,raw_user_meta_data) select pg_temp.k(name),'pb-'||name||'@fixture.local',jsonb_build_object('display_name',name) from unnest(array['agency','client','designer','other']) name;
update profiles set role='agency' where id=pg_temp.k('agency');
update profiles set role='designer' where id in(pg_temp.k('designer'),pg_temp.k('other'));
insert into clients(id,name,slug) values(pg_temp.k('client-org'),'Production brief test','production-brief-test');
insert into client_memberships(client_id,user_id) values(pg_temp.k('client-org'),pg_temp.k('client'));
insert into briefings(id,client_id,title,service_type,overview,status,created_by,direction,requested_deliverables)
 values(pg_temp.k('brief'),pg_temp.k('client-org'),'Client request','social','Original private request','accepted',pg_temp.k('client'),'{"questions":{"content":"I’ll provide the content"}}',
 '[{"name":"One final","format":"feed","width":1080,"height":1350,"quantity":1,"scope":"original"}]');
insert into projects(id,client_id,briefing_id,title,description,service_type,due_date,start_date) values(pg_temp.k('project'),pg_temp.k('client-org'),pg_temp.k('brief'),'Project title','Original private request','social','2026-10-05','2026-09-28');
insert into project_assignments(project_id,designer_id) values(pg_temp.k('project'),pg_temp.k('designer')),(pg_temp.k('project'),pg_temp.k('other'));
insert into design_boards(id,project_id,name,designer_id,board_id,created_by) values(pg_temp.k('board'),pg_temp.k('project'),'Concepts',pg_temp.k('designer'),'uXjVTest001=',pg_temp.k('agency')),(pg_temp.k('other-board'),pg_temp.k('project'),'Other board',pg_temp.k('other'),'uXjVTest002=',pg_temp.k('agency'));
insert into deliverables(project_id,name,format,width,height,quantity) values(pg_temp.k('project'),'One final','feed',1080,1350,1);
insert into briefing_attachments(briefing_id,name,storage_path,mime_type,file_size) values(pg_temp.k('brief'),'Client notes.pdf',pg_temp.k('brief')||'/notes.pdf','application/pdf',12);

select pg_temp.act('designer'); set local role authenticated;
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content(),0,true,pg_temp.k('send-key'))$$,'42501',null,'Designer cannot author production instructions');
select is((select count(*)::int from get_assigned_briefings(pg_temp.k('client-org'))),0,'Legacy projection releases no client brief');
select is((select count(*)::int from briefings where id=pg_temp.k('brief')),0,'Designer cannot read original briefing');
select is((select count(*)::int from deliverables where project_id=pg_temp.k('project')),0,'Designer cannot read contracted quantities');
select is((select count(*)::int from briefing_attachments where briefing_id=pg_temp.k('brief')),0,'Designer cannot read original attachments');
select is(private.can_access_briefing(pg_temp.k('brief')),false,'Original attachment storage access is denied');
select throws_ok($$select description from projects where id=pg_temp.k('project')$$,'42501',null,'Direct description reads are denied');
select is((select description from visible_projects() where id=pg_temp.k('project')),'','Designer project description cannot reproduce original request');
reset role;
select pg_temp.act('client'); set local role authenticated;
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content(),0,true,pg_temp.k('send-key'))$$,'42501',null,'Client cannot author internal instructions');
select is((select description from visible_projects() where id=pg_temp.k('project')),'Original private request','Client retains their project description');
select is((select count(*)::int from deliverables where project_id=pg_temp.k('project')),1,'Client keeps their contracted output');
reset role;
select pg_temp.act('agency'); set local role authenticated;
select is(save_production_brief(pg_temp.k('board'),pg_temp.content(),0,false,pg_temp.k('draft-key')),1,'Agency saves a private draft');
select is(save_production_brief(pg_temp.k('board'),pg_temp.content(),0,false,pg_temp.k('draft-key')),1,'Draft retry is idempotent');
select is((select count(*)::int from production_briefs where board_id=pg_temp.k('board')),0,'Draft does not release instructions');
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content(),0,true,pg_temp.k('send-key'))$$,'40001',null,'Stale editor cannot overwrite a newer draft');
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content()||'{"dueDate":"2026-10-06"}',1,true,pg_temp.k('send-key'))$$,'22023',null,'Internal deadline cannot exceed client deadline');
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content()||'{"deliverables":[]}',1,true,pg_temp.k('send-key'))$$,'22023',null,'Cannot send an empty production scope');
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content()||'{"references":[{"name":"bad","url":"javascript:alert(1)"}]}',1,true,pg_temp.k('send-key'))$$,'22023',null,'Unsafe reference URLs are rejected');
select throws_ok($$select save_production_brief(pg_temp.k('board'),pg_temp.content()||'{"references":[{"name":"bad","url":"https://name:secret@example.com/file"}]}',1,true,pg_temp.k('send-key'))$$,'22023',null,'Reference credentials are refused in the database');
select throws_ok($$select save_production_brief(pg_temp.k('board'),jsonb_set(pg_temp.content(),'{deliverables,0}',(pg_temp.content()->'deliverables'->0)-'width'),1,true,pg_temp.k('send-key'))$$,'22023',null,'Sized production outputs require dimensions in the database');
select is(save_production_brief(pg_temp.k('board'),pg_temp.content(),1,true,pg_temp.k('send-key')),2,'Agency sends production instructions');
select is(save_production_brief(pg_temp.k('board'),pg_temp.content(),1,true,pg_temp.k('send-key')),2,'Publish retry does not send again');
select is((select due_date from design_boards where id=pg_temp.k('board')),'2026-10-01'::date,'Sending sets the board deadline');
select is((select due_date from projects where id=pg_temp.k('project')),'2026-10-05'::date,'Project deadline stays intact');
select is((select requested_deliverables->0->>'quantity' from briefings where id=pg_temp.k('brief')),'1','Client scope stays intact');
select is(save_production_brief(pg_temp.k('board'),pg_temp.content()||'{"overview":"Private draft changes"}',2,false,pg_temp.k('edit-key')),3,'Agency can revise a draft after sending');
reset role;
select is((select count(*)::int from notifications where project_id=pg_temp.k('project') and title='Production brief updated'),1,'One notification for the actual publish');
select is((select user_id from notifications where project_id=pg_temp.k('project') and title='Production brief updated'),pg_temp.k('designer'),'Only this board designer is notified');
select pg_temp.act('designer'); set local role authenticated;
select is((select count(*)::int from production_brief_drafts),0,'Designer receives no drafts');
select is((select content->>'overview' from production_briefs where board_id=pg_temp.k('board')),'Create three distinct options','Unsent changes do not replace released instructions');
select is((select content->'deliverables'->0->>'quantity' from production_briefs where board_id=pg_temp.k('board')),'3','Designer sees only production quantity');
reset role;
select pg_temp.act('other'); set local role authenticated;
select is((select count(*)::int from production_briefs),0,'Another assigned designer cannot read this board brief');
reset role;
select pg_temp.act('client'); set local role authenticated;
select is((select count(*)::int from production_briefs),0,'Client receives no production instructions');
select is((select count(*)::int from production_brief_drafts),0,'Client receives no drafts');
reset role;
delete from project_assignments where project_id=pg_temp.k('project') and designer_id=pg_temp.k('designer');
select pg_temp.act('designer'); set local role authenticated;
select is((select count(*)::int from production_briefs),0,'Revocation removes production brief access');
reset role;
select * from finish();
rollback;
