begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(14);
-- Match the Storage API delete transaction guard while evaluating its RLS policies.
set local storage.allow_delete_query='true';
select is((select count(*)::int from public.service_catalog),20,'Canonical service catalog has 20 types');
select is((select count(*)::int from public.format_catalog),25,'Canonical format catalog has 25 formats');
select set_config('request.jwt.claim.sub',md5('dawes:agency')::uuid::text,true);
set local role authenticated;
select ok(not has_function_privilege('authenticated','public.register_sanitized_asset(uuid,text,text,text,text,bigint,uuid,uuid,text)','execute'),'Browser sessions cannot attest to sanitized bytes');
select throws_ok($$insert into storage.objects(bucket_id,name,owner_id) values('published-assets',md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png',auth.uid()::text)$$,'42501',null,'Agency cannot bypass the worker by uploading publication bytes directly');
select throws_ok($$insert into storage.objects(bucket_id,name,owner_id) values('delivery-files',md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png',auth.uid()::text)$$,'42501',null,'Agency cannot bypass the worker by uploading delivery bytes directly');
reset role;
insert into storage.objects(bucket_id,name,metadata) values('published-assets',md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png','{"size":100}');
update public.designs set internal_asset_path=project_id::text||'/'||md5('internal-source')::uuid::text||'.png' where id=md5('dawes:design-16-2-0')::uuid;
set local role authenticated;
select throws_ok($$select public.publish_version(md5('dawes:version-16-2')::uuid,'Prepared output',jsonb_build_object(md5('dawes:design-16-2-0')::uuid::text,md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png'))$$,'P0001','A trusted sanitized publication asset is required for this design','Unregistered files cannot enter a client publication');
reset role;
select set_config('request.jwt.claim.role','service_role',true);
set local role service_role;
select lives_ok($$select public.register_sanitized_asset(md5('dawes:project-16')::uuid,'published-assets',md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png',repeat('a',64),'image/png',100,md5('dawes:agency')::uuid,md5('dawes:design-16-2-0')::uuid,md5('dawes:project-16')::uuid::text||'/'||md5('internal-source')::uuid::text||'.png')$$,'Trusted worker can register a scoped regenerated object');
reset role;
select set_config('request.jwt.claim.role','authenticated',true);
set local role authenticated;
select lives_ok($$select public.publish_version(md5('dawes:version-16-2')::uuid,'Prepared output',jsonb_build_object(md5('dawes:design-16-2-0')::uuid::text,md5('dawes:project-16')::uuid::text||'/'||md5('trusted-output')::uuid::text||'.png'))$$,'Agency can publish the registered sanitized object');
reset role;
update public.briefings set direction='{}' where id=md5('dawes:pending-1')::uuid;
select set_config('request.jwt.claim.sub',md5('dawes:client-1')::uuid::text,true);
set local role authenticated;
select throws_ok($$select public.submit_briefing(md5('dawes:pending-1')::uuid)$$,'P0001','Answer every service question before submitting','Direct API submission cannot omit service answers');
reset role;
update public.briefings set direction='{"questions":{"content":"Invented option"}}' where id=md5('dawes:pending-1')::uuid;
set local role authenticated;
select throws_ok($$select public.submit_briefing(md5('dawes:pending-1')::uuid)$$,'P0001','Choose an allowed option for each service question','Direct API submission cannot invent catalog options');
reset role;
select set_config('request.jwt.claim.sub',md5('dawes:agency')::uuid::text,true);
insert into storage.objects(bucket_id,name) values('brand-assets',md5('dawes:client-org-1')::uuid::text||'/'||md5('brand-orphan')::uuid::text||'.png');
insert into storage.objects(bucket_id,name) values('brand-assets',md5('dawes:client-org-1')::uuid::text||'/'||md5('brand-registered')::uuid::text||'.png');
insert into public.brand_assets(client_id,name,category,storage_path) values(md5('dawes:client-org-1')::uuid,'Brand image','Photography',md5('dawes:client-org-1')::uuid::text||'/'||md5('brand-registered')::uuid::text||'.png');
set local role authenticated;
with deleted as (delete from storage.objects where bucket_id='brand-assets' and name like '%'||md5('brand-orphan')::uuid::text||'.png' returning name) select is((select count(*)::int from deleted),1,'Agency can remove an unregistered brand object');
with deleted as (delete from storage.objects where bucket_id='brand-assets' and name like '%'||md5('brand-registered')::uuid::text||'.png' returning name) select is((select count(*)::int from deleted),0,'Referenced brand bytes cannot be deleted');
reset role;
select set_config('request.jwt.claim.sub',md5('dawes:client-1')::uuid::text,true);
set local role authenticated;
with deleted as (delete from storage.objects where bucket_id='brand-assets' returning name) select is((select count(*)::int from deleted),0,'Client cannot delete shared brand files');
select ok(not has_table_privilege('authenticated','private.sanitized_assets','select'),'Trusted attestations do not expose internal source metadata');
select * from finish();
rollback;
